export type BucketKey = "contact" | "giveaway" | "payment" | "spam";

export const GlobalBucketDataset: Record<BucketKey, string[]> = {
  contact: [
    "dm me",
    "message me privately",
    "contact me on",
    "add me on discord",
    "my telegram is",
    "reach me on whatsapp",
    "send me a friend request",
    "follow me on",
    "hit me up on",
    "my instagram is",
    "my snap is",
    "find me on",
  ],
  giveaway: [
    "free nitro",
    "steam gift card",
    "you have won",
    "you won a",
    "claim your prize",
    "click to claim",
    "free robux",
    "congratulations you have been selected",
    "you have been selected",
    "limited time giveaway",
    "act now to claim",
    "discord nitro giveaway",
    "steam key giveaway",
  ],
  payment: [
    "cashapp me",
    "send btc",
    "bitcoin address",
    "send crypto",
    "ethereum payment",
    "paypal friends and family",
    "venmo me",
    "zelle me",
    "wire transfer",
    "western union",
    "moneygram",
    "send usdt",
    "my wallet address",
  ],
  spam: [
    "join my server",
    "check out my server",
    "buy discord accounts",
    "sell discord accounts",
    "cheap nitro",
    "nitro for sale",
    "server boosts for sale",
    "buy followers",
    "boost your server cheap",
    "click my link",
    "promo code",
    "advertise your server",
  ],
};
