name: Build and Deploy Canary with PM2

on:
  push:
    branches: [canary]

jobs:
  deploy:
    runs-on: [self-hosted,canary]
    env:
      BOT_TOKEN_CANARY: ${{ secrets.BOT_TOKEN_CANARY }}
      BOT_DB: ${{ secrets.BOT_DB }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_CANARY }}
      CLIENT_ID: ${{ secrets.CLIENT_ID_CANARY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_CANARY }}

    steps:
      - name: 👤 Show current user
        run: whoami
    
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Install dependencies
        run: |
          npm ci

      - name: 🧱 Build TypeScript
        run: |
          npm run build

      - name: 🔗 Create Environment Variables
        run: |
          echo "TOKEN=${BOT_TOKEN_CANARY}" >> .env
          echo "DATABASE=${BOT_DB}" >> .env
          echo "CLIENT_SECRET={CLIENT_SECRET}"
          echo "CLIENT_ID={CLIENT_ID}"
          echo "JWT_TOKEN={JWT_TOKEN}"

      - name: 🚀 Restart app with PM2
        run: |
          pm2 startOrRestart pm2.config.js --only olive
