name: Build and Deploy with PM2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, lxc, nosudo]

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Install dependencies
        run: |
          npm ci

      - name: 🧱 Build TypeScript
        run: |
          npm run build

      - name: 📦 Move .env to dist
        run: cp .env dist/.env

      - name: 🚀 Restart app with PM2
        run: |
          cd dist
          pm2 startOrRestart ../pm2.config.js --only olive