name: Build and Deploy with PM2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 👤 Show current user
        run: whoami
    
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Install dependencies
        run: |
          npm ci

      - name: 🧱 Build TypeScript
        run: |
          npm run build

      - name: 🔗 Symlink .env.local to .env in repo
        run: ln -sf /root/actions-runner/.env.local .env
        working-directory: /root/actions-runner/_work/olive/olive

      - name: 🚀 Restart app with PM2
        run: |
          pm2 startOrRestart pm2.config.js --only olive
