name: Build and Deploy with PM2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_DB: ${{ secrets.BOT_DB }}

    steps:
      - name: 👤 Show current user
        run: whoami
    
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Install dependencies
        run: |
          npm ci

      - name: 🧱 Build TypeScript
        run: |
          npm run build

      - name: 🔗 Create Environment Variables
        run: |
          echo "TOKEN=${BOT_TOKEN}" >> .env
          echo "DATABASE=${BOT_DB}" >> .env

      - name: 🚀 Restart app with PM2
        run: |
          pm2 startOrRestart pm2.config.js --only olive
